const issuesData = [
  {
    id: 1,
    title: "Pothole on Main Road Near School",
    description: "Large pothole causing traffic issues and safety concerns for students walking to school every morning.",
    location: "Baneshwor Main Road",
    ward: "Ward 32",
    category: "Roads",
    status: "In Progress",
    image: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=600&q=80",
    upvotes: 127,
    comments: 23,
    reporter: "Ramesh Sharma",
    timeAgo: "2 days ago",
  },
  {
    id: 2,
    title: "Broken Street Light at Junction",
    description: "Street light has been non-functional for over a week causing major visibility issues at night for commuters.",
    location: "Koteshwor Chowk",
    ward: "Ward 35",
    category: "Electricity",
    status: "Open",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    upvotes: 89,
    comments: 11,
    reporter: "Sita Thapa",
    timeAgo: "5 hours ago",
  },
  {
    id: 3,
    title: "Garbage Pile Near Residential Area",
    description: "Uncollected garbage for 5 days creating serious health hazards and unbearable smell for nearby residents.",
    location: "Lalitpur, Ward 10",
    ward: "Ward 10",
    category: "Sanitation",
    status: "Resolved",
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&q=80",
    upvotes: 203,
    comments: 47,
    reporter: "Bikash Maharjan",
    timeAgo: "1 week ago",
  },
  {
    id: 4,
    title: "Water Pipeline Leakage",
    description: "Major water pipe burst wasting thousands of litres daily and progressively damaging the road surface.",
    location: "Patan Dhoka Road",
    ward: "Ward 18",
    category: "Water Supply",
    status: "In Progress",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
    upvotes: 54,
    comments: 8,
    reporter: "Anita Shrestha",
    timeAgo: "3 days ago",
  },
  {
    id: 5,
    title: "Damaged Footpath Blocks Pedestrians",
    description: "Cracked and severely uneven footpath is extremely dangerous for elderly people and children.",
    location: "New Baneshwor",
    ward: "Ward 31",
    category: "Infrastructure",
    status: "Open",
    image: "https://images.unsplash.com/photo-1619468129361-605ebea04b44?w=600&q=80",
    upvotes: 72,
    comments: 15,
    reporter: "Deepak Karki",
    timeAgo: "1 day ago",
  },
  {
    id: 6,
    title: "Illegal Encroachment on Public Land",
    description: "New construction is blocking community park entrance that residents have used freely for decades.",
    location: "Balkhu Ring Road",
    ward: "Ward 14",
    category: "Land",
    status: "Open",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
    upvotes: 341,
    comments: 62,
    reporter: "Raju Lama",
    timeAgo: "4 days ago",
  },
];